- hosts: webservers
  become: yes
  vars:
    http_port: 8000
    https_port: 4443
    html_welcome_msg: "Hello world!"
  roles:
    - apache2
    - common 

- hosts: proxy
  become: yes
  roles:
    - common
    - nginx